import { Component, Input } from '@angular/core';
import { HeroComponent } from './hero/hero.component';

@Component({
    selector: 'my-app',
    templateUrl: './app/app.component.html',
    styleUrls: ['./app/app.component.css']

})
export class AppComponent {

    title: string;
    heros: any;
    selectedHero: HeroComponent
    constructor() {
        this.title = "Tour of Heroes";
        const HEROES: HeroComponent[] = [
            { id: 11, name: 'Batman', p1: "Who else? You can go through literally every era of Batman comics and pick out multiple tales which have well-deserved 'classic' status, with tales like The Killing Joke, Year One, The Dark Knight Returns, and even Scott Snyder's current run all bringing something truly special to the table.", p2: "Bruce Wayne is a character like no other; he may be absurdly wealthy and ridiculously well trained, but he's still just a man. However, that doesn't stop him from standing every bit as tall as the rest of the Justice League and frequently overcoming the kind of odds his superpowered teammates couldn't even begin to fathom. There's just no one and nothing else like The Batman. ", image: 'http://105.imagebam.com/download/rCB5zJXKjJLHNCVC43GG3Q/47142/471413010/Batman.png' },
            { id: 12, name: ' Spider-Man', p1: "Placing Spider-Man on this list was tough. He's MY favourite superhero, but I know that doesn't necessarily mean he's a great character. However, common sense says that he is, something which has really been evident from day one; simply put, the wall-crawler is easily Marvel's best creation.", p2: "Despite loss after loss, Spidey keeps on fighting, never giving up and always doing what's right. Still, he's not a goody two shoes and is just as flawed as the rest of us. Yes, he has spectacular powers and has gone so far as saving the entire planet on occasion, but Peter Parker is also Marvel's most human hero. It's that which make his adventures timeless, and he'll certainly outlive us all.", image: 'http://105.imagebam.com/download/Z0BCwy7MUSO5ahutWdI16w/47142/471412967/Spider-Man.png' },
            { id: 13, name: 'Wonder Woman', p1: "Wonder Woman may not have had much luck in live-action (something which is hopefully going to change later this month), but can you honesty think of a greater female character in comics? With a fascinating origin story - both before and after The New 52 reboot - Diana Prince has a ton of mythology behind her and a lot of great stories which span decades.", p2: "A feminist symbol to begin with, Wonder Woman has become much more than that, and is a hero who both young girls AND boys can now look up to. A member of the Justice League and an irreplaceable part of The Trinity, the DC Universe wouldn't be the same without her, and, well, neither would the superhero genre.", image: 'http://105.imagebam.com/download/CunzhbRKHvRYg4u8J9iuGg/47142/471412866/Wonder%20Woman.png' },
            { id: 14, name: 'Captain America', p1: "Captain America is a tough character to write, especially as many writers tend to go a overboard with his patriotic side. However, that all changed when Ed Brubaker gave him a modern makeover in a run which still stands out as the best yet featuring the character.", p2: "Even before then though, Steve Rogers has had plenty of great moments, and while Stan Lee didn't create him, he may as well have because everything changed for Cap when he became an Avenger. Whether it's assembling a cooky quartet, standing up to Thanos, or protecting his fellow heroes by standing up to the government, Steve is a symbol for not just what makes America great, but greatness itself.", image: 'http://114.imagebam.com/download/H2P-39K3j6Eu3E-DWTHZew/47142/471412741/Captain%20America%207.png' },
            { id: 15, name: 'The Flash', p1: "Depending on how old you are or just your own personal preference, 'The Flash' could refer to either Barry Allen or Wally West. Regardless of which version of The Fastest Man Alive you call your own, their adventures both together and apart are undeniably among the best in comic book history.", p2: "From Wally's war with Zoom to Barry's many trips through time and an ultimate sacrifice in the iconic Crisis on Infinite Earths, The Flash has become synonymous with quality storytelling, and he's by far the best speedster on the stands every month (sorry, Quicksilver). Unlike many other heroes, Barry and Wally don't really have a dark side; they're just good guys. ", image: 'http://114.imagebam.com/download/jKfOZti48zQewWscY7uP4w/47142/471412808/Flash.png' },
            { id: 16, name: 'Daredevil', p1: "Even now he's starring in a critically acclaimed Netflix series, is Daredevil really on the A-List? Honestly, the fact he's always flown under that top tier of superheroes is what's made him so great, especially when you look at the work of writers like Frank Miller, Brian Michael Bendis, Ed Brubaker, and Mark Waid.", p2: "One of the only heroes with a true disability, Matt Murdock's battle with depression also grounds him in reality in a way even his dark and gritty adventures don't. His rogues gallery is also one of the most underrated in comics, and The Man Without Fear's battles with the likes of Bullseye and The Kingpin are often much better than the flashy stuff you get in other titles!", image: 'http://114.imagebam.com/download/HP0Abx7eqwyzuKf5OKC_kQ/47142/471412834/Daredevil%201.png' },
            { id: 17, name: 'Superman', p1: "So, you were probably expecting Superman to place a little higher than this, right? To be blunt, I'm not a massive fan of the Man of Steel, but he is a character with plenty of amazing moments, and his importance to the success of superhero comic books can't be denied.", p2: "When you picture an archetypical 'superhero', it's Superman who first comes to mind, and regardless of whether you love the classic John Byrne Supes or the edgier New 52 version, chances are that you'll appreciate him for one reason or another. The Justice League wouldn't be the same without him, that's for sure, and he's one of the only characters who even those who don't read comics are familiar with.", image: 'http://114.imagebam.com/download/77d3Uhgj3jCpgMxzYbmM2Q/47142/471412780/Superman.png' },
            { id: 18, name: 'Iron Man', p1: "Robert Downey Jr.'s stint as Iron Man has not only had a massive impact on the superhero movie genre, but also how Tony Stark is portrayed in the comic books. However, even before the Armoured Avenger underwent something of a personality shift, he was still a pretty damn awesome character.", p2: "A founding member of Earth's Mightiest Heroes, Iron Man may have been a B-List tier hero for many years, but he's one of Stan Lee's best creations, years ahead of his time, and still bringing a fascinating technological edge to the Marvel Universe. Sure, he was an asshole during Civil War, but if you can forgive him for that, I think you'll agree with this assessment.", image: 'http://114.imagebam.com/download/wF0BTPuQgeCzhOkBM8RaNA/47142/471412898/Iron%20Man.png' },
            { id: 19, name: 'The Invisible Woman', p1: "Sue Storm may not be the 'coolest' member of the Fantastic Four or the one most beloved by fans, but she IS a great character. Created during a sexist period in which she was known as The Invisible 'Girl'  and often portrayed as little more than a damsel in distress, Sue has gone on to prove herself as the most powerful member of this team, and the glue which holds Marvel's very dysfunctional First Family together", p2: "A wife, mother, sister, and friend, The Invisible Woman is pretty damn inspirational when you think about it, and of Marvel's many great female characters, I think it's fair to say that she ultimately stands out as being the best, despite not being the most iconic.", image: 'http://114.imagebam.com/download/BtrwZ19ne17i81d9jxFeyA/47142/471413032/Invisible%20Woman.png' },
            { id: 20, name: 'Wolverine', p1: "The funny thing about Wolverine is that even if you're not a massive fan of the character, there's a very good chance that you love at least one of his adventures. This mutant has been through so much over the years that there really is something for everyone, whether it's a classic like the Japan Saga or  a modern great like Old Man Logan.", p2: "While I'm not necessarily saying that Wolverine is the best X-Man (for me, that's a title which goes to Cyclops), his lasting appeal as a member of that team - and many others - as well as a solo hero speaks volumes, and while Marvel currently have him on the bench, here's hoping James Howlett is back in action pretty soon.", image: 'http://114.imagebam.com/download/E2VwlTP4JvZb_NWDGM2yNQ/47142/471413074/Wolverine.png' }
        ];
        this.heros = HEROES;
    }

    onSelect(hero: HeroComponent): void {
        this.selectedHero = hero;
    }


}
